# Generated by Django 3.2 on 2021-05-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210428_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='vounty',
            name='comment_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='vounty',
            name='entry_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
