# Generated by Django 3.2 on 2021-06-02 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210506_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_comment', models.BooleanField(default=False)),
                ('new_entry', models.BooleanField(default=False)),
                ('new_fund', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vounty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vounty')),
            ],
        ),
    ]
