# Generated by Django 3.2 on 2021-06-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='vounty',
            name='reddit',
            field=models.TextField(blank=True, default=''),
        ),
    ]
